name: Test

on:
  - push
  - pull_request

jobs:
  build:
    # As long as we need Python 3.6 here in the test, we can only use up to Ubuntu 20.
    # https://github.com/actions/setup-python/issues/544
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: '3.6'
            toxenv: py36
          - python-version: '3.7'
            toxenv: py37
          - python-version: '3.8'
            toxenv: py38
          - python-version: '3.9'
            toxenv: py39
          - python-version: '3.9'
            toxenv: desc

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox -v
